name: Deploy Django to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd users  # Move into the users directory
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Run migrations
#        env:
#          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
#          RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
#          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
#          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
#          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
#          RDS_PORT: ${{ secrets.RDS_PORT }}
#        run: |
#          cd users  # Move into the users directory
#          python manage.py migrate

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
        run: |
          cd users  # Move into the users directory
          # Debug Environment Variables
          echo "EB_APPLICATION_NAME=$EB_APPLICATION_NAME"
          echo "EB_ENVIRONMENT_NAME=$EB_ENVIRONMENT_NAME"
          
          eb init $EB_APPLICATION_NAME --region $AWS_REGION --platform "Python 3.12"
          
          # Check if dir created
          ls -ltra
          
          eb deploy $EB_ENVIRONMENT_NAME