name: Deploy Django to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd users  # Move into the users directory
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Environment Variables
        run: |
          echo "RDS_DB_NAME=${{ secrets.RDS_DB_NAME }}"
          echo "RDS_DB_USER=${{ secrets.RDS_DB_USER }}"
          echo "RDS_DB_HOST=${{ secrets.RDS_DB_HOST }}"
          echo "RDS_DB_PORT=${{ secrets.RDS_DB_PORT }}"
          echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}"

#      - name: Run migrations
#        run: |
#          cd users  # Move into the users directory
#
#          export RDS_DB_NAME="${{ secrets.RDS_DB_NAME }}"
#          export RDS_DB_USER="${{ secrets.RDS_DB_USER }}"
#          export RDS_DB_PASSWORD="${{ secrets.RDS_DB_PASSWORD }}"
#          export RDS_DB_HOST="${{ secrets.RDS_DB_HOST }}"
#          export RDS_DB_PORT="${{ secrets.RDS_DB_PORT }}"
#
#          echo "RDS_DB_NAME=$RDS_DB_NAME"
#          echo "RDS_DB_HOST=$RDS_DB_HOST"
#
#          python manage.py migrate

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          pip install awsebcli --upgrade

      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
        run: |
          cd users  # Move into the users directory
          eb init $EB_APPLICATION_NAME --region $AWS_REGION --platform "Python 3.12"
          eb deploy $EB_ENVIRONMENT_NAME
